{application, spider,
 [{description, "Web spider"},
  {id, "spider"},
  {vsn, "1.0"},
  {modules, [spider_app,
             spider_sup,
             fetcher_sup,
             fetcher,
             stats_collector,
             task_master]},
  {registered, [spider_sup,
                fetcher_sup,
                stats_collector,
                task_master]},
  {applications, [kernel, stdlib, inets]},
  {included_applications, [inets]},
  {mod, {spider_app, [{pool_size, 5}]}}]}.
